const $=s=>document.querySelector(s);
const screens=['home','preview','analysing','setup','confirm','result'];
let photoURL='', currentCard=null;
const DEMO={name:'Lightning Greaves',type_line:'Artifact — Equipment',image:'https://cards.scryfall.io/normal/front/d/3/d36d5d92-7a8d-4df1-a098-5e21af73369d.jpg',oracle:'Equipped creature has haste and shroud. Equip {0}.',keywords:[['Haste','The equipped creature can attack and use tap abilities immediately, even if it only entered this turn.'],['Shroud','Nobody can target the equipped creature, including you. This protects it, but also stops you attaching another Aura, Equipment or targeted effect to that creature.']]};
function show(id){screens.forEach(x=>$('#'+x).classList.toggle('active',x===id));scrollTo({top:0,behavior:'smooth'})}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('on');setTimeout(()=>$('#toast').classList.remove('on'),1900)}
function openCamera(){ $('#cameraInput').click() }
$('#cameraBtn').onclick=openCamera;
$('#cameraInput').onchange=e=>{const f=e.target.files?.[0];if(!f)return;if(photoURL)URL.revokeObjectURL(photoURL);photoURL=URL.createObjectURL(f);$('#photo').src=photoURL;show('preview')};
$('#retakeBtn').onclick=openCamera;
$('#identifyBtn').onclick=async()=>{show('analysing');$('#analysisStatus').textContent='Reading the name, art and card frame.';try{const r=await fetch('/api/identify',{method:'POST',headers:{'Content-Type':eMime()},body:await fileBody()});if(!r.ok)throw new Error('not-connected');const data=await r.json();if(!data.card_name)throw new Error('no-match');const card=await lookup(data.card_name);if(!card)throw new Error('no-match');currentCard=normalise(card,data.confidence);fillConfirm(currentCard);show('confirm')}catch(e){setTimeout(()=>show('setup'),500)}};
function eMime(){return $('#cameraInput').files?.[0]?.type||'image/jpeg'}
async function fileBody(){return await $('#cameraInput').files[0].arrayBuffer()}
async function lookup(name){try{const r=await fetch('https://api.scryfall.com/cards/named?fuzzy='+encodeURIComponent(name));return r.ok?await r.json():null}catch{return null}}
function normalise(c,confidence){return{name:c.name,type_line:c.type_line,image:c.image_uris?.normal||c.card_faces?.[0]?.image_uris?.normal||'',oracle:(c.card_faces||[c]).map(f=>f.oracle_text||'').filter(Boolean).join('\n—\n'),confidence,keywords:detect((c.card_faces||[c]).map(f=>f.oracle_text||'').join(' '))}}
const defs={haste:'This creature can attack and use tap abilities immediately.',flying:'This creature can only be blocked by creatures with flying or reach.',reach:'This creature can block creatures with flying.',vigilance:'Attacking does not tap this creature, so it can still block.',trample:'After assigning lethal damage to blockers, extra damage can hit the defending player.',deathtouch:'Any amount of damage this deals to a creature is lethal.',lifelink:'Damage it deals also gains you that much life.',flash:'You may cast it whenever you could cast an instant.',hexproof:'Opponents cannot target it, but you still can.',shroud:'Nobody can target it, including you.',ward:'An opponent who targets it must pay the ward cost or that spell or ability is countered.',equip:'Pay the equip cost at sorcery speed to attach this Equipment to a creature you control.'};
function detect(t){const l=t.toLowerCase();return Object.entries(defs).filter(([k])=>l.includes(k)).map(([k,v])=>[k,v])}
$('#demoBtn').onclick=()=>{currentCard=DEMO;fillConfirm(DEMO);show('confirm')};
function fillConfirm(c){$('#matchedImage').src=c.image;$('#matchedName').textContent=c.name;$('#matchedType').textContent=c.type_line;$('#confidence').textContent=c.confidence?`${Math.round(c.confidence)}% MATCH`:'DEMO MATCH'}
$('#yesBtn').onclick=()=>{render(currentCard);show('result')};
$('#noBtn').onclick=openCamera;$('#confirmBack').onclick=()=>show('preview');$('#anotherBtn').onclick=openCamera;
document.querySelectorAll('[data-home]').forEach(b=>b.onclick=()=>show('home'));
function render(c){$('#resultImage').src=c.image;$('#resultName').textContent=c.name;$('#resultType').textContent=c.type_line;const low=c.oracle.toLowerCase(),type=c.type_line.toLowerCase();let timing=type.includes('instant')||low.includes('flash')?'Hold it until the effect matters. Waiting keeps your options open and gives opponents less information.':type.includes('sorcery')?'Cast it during your own main phase, when the board and targets make the effect worthwhile.':type.includes('creature')?'Play it in a main phase to develop your board. Unless it has haste, it normally cannot attack until your next turn.':'Most permanents are best played during your main phase, when you can afford them without giving up an urgent response.';let use=low.includes('equip')?'Play a creature first, then attach this when you can also afford the equip cost. Move it when another creature becomes the better carrier.':low.includes('destroy')||low.includes('exile target')?'Save it for a threat that matters rather than spending it on the first legal target.':'Decide what job the card performs: developing your board, protecting something, answering a threat or helping finish the game.';let watch=low.includes('shroud')?'Shroud also stops your own targeted spells and abilities. Attach or target anything else you need before giving the creature shroud.':low.includes('target')?'The target must still be legal when the spell or ability resolves.':'Think about the removal, blockers or responses an opponent may still have before you commit it.';$('#explanation').innerHTML=block(1,'WHAT IT DOES',`<p>${esc(c.oracle)}</p>`)+block(2,'WORDS WORTH KNOWING',c.keywords.length?c.keywords.map(([k,v])=>`<div class="keyword"><b>${esc(k)}</b>${esc(v)}</div>`).join(''):'<p>No major keyword needs translating on this card.</p>')+block(3,'WHEN TO PLAY IT',`<p>${timing}</p>`)+block(4,'HOW TO USE IT WELL',`<p>${use}</p>`)+block(5,'WATCH OUT FOR',`<p>${watch}</p>`)}
function block(n,h,b){return`<section class="explain-block"><h3><span class="num">${n}</span>${h}</h3>${b}</section>`}function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('#shareBtn').onclick=async()=>{try{await navigator.share({title:`${currentCard.name} — SpellCheck`,text:`SpellCheck explained ${currentCard.name}.`,url:location.href})}catch{toast('SHARING CANCELLED')}};
$('#aboutBtn').onclick=()=>$('#aboutDialog').showModal();$('#closeAbout').onclick=()=>$('#aboutDialog').close();
