const $=s=>document.querySelector(s);
const screens=['home','preview','analysing','setup','confirm','result'];
let photoURL='',currentCard=null;
const DEMO={name:'Lightning Greaves',type_line:'Artifact — Equipment',image:'https://cards.scryfall.io/normal/front/d/3/d36d5d92-7a8d-4df1-a098-5e21af73369d.jpg',oracle:'Equipped creature has haste and shroud. Equip {0}.',confidence:null,keywords:[['Haste','The equipped creature can attack and use tap abilities immediately, even if it entered this turn.'],['Shroud','Nobody can target the equipped creature, including its controller.']]};
const definitions={haste:'The creature can attack and use tap abilities immediately, even if it entered this turn.',flying:'The creature can only be blocked by creatures with flying or reach.',reach:'The creature can block creatures with flying.',vigilance:'Attacking does not tap the creature, so it remains available to block.',trample:'After lethal damage is assigned to blockers, excess damage may be dealt to the defending player.',deathtouch:'Any amount of damage this deals to a creature is lethal.',lifelink:'Damage dealt by this source also gains its controller that much life.',flash:'This may be cast whenever an instant could be cast, including during another player’s turn.',hexproof:'Opponents cannot target it, although its controller still can.',shroud:'Nobody can target it, including its controller.',ward:'An opponent who targets it must pay the ward cost or that spell or ability is countered.',equip:'Pay the equip cost as a sorcery to attach this Equipment to a creature you control.',menace:'The creature cannot be blocked by only one creature.',indestructible:'Damage and effects that say “destroy” do not destroy it. Exile, sacrifice and zero toughness can still remove it.',scry:'Look at that many cards from the top of the library, place any on the bottom, then return the remainder to the top.'};
function show(id){screens.forEach(x=>$('#'+x).classList.toggle('active',x===id));window.scrollTo({top:0,behavior:'smooth'})}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('on');setTimeout(()=>$('#toast').classList.remove('on'),1800)}
function openCamera(){ $('#cameraInput').value='';$('#cameraInput').click() }
$('#cameraBtn').onclick=openCamera;$('#retakeBtn').onclick=openCamera;$('#noBtn').onclick=openCamera;$('#anotherBtn').onclick=openCamera;
$('#cameraInput').onchange=e=>{const file=e.target.files?.[0];if(!file)return;if(photoURL)URL.revokeObjectURL(photoURL);photoURL=URL.createObjectURL(file);$('#photo').src=photoURL;show('preview')};
document.querySelectorAll('[data-home]').forEach(b=>b.onclick=()=>show('home'));
$('#confirmBack').onclick=()=>show('preview');
$('#identifyBtn').onclick=async()=>{show('analysing');try{const file=$('#cameraInput').files[0];const response=await fetch('/api/identify',{method:'POST',headers:{'Content-Type':file.type||'image/jpeg'},body:await file.arrayBuffer()});if(!response.ok)throw new Error('not connected');const match=await response.json();if(!match.card_name)throw new Error('no match');const card=await lookup(match.card_name);if(!card)throw new Error('not found');currentCard=normalise(card,match.confidence);fillConfirm(currentCard);show('confirm')}catch(e){setTimeout(()=>show('setup'),500)}};
async function lookup(name){try{const r=await fetch('https://api.scryfall.com/cards/named?fuzzy='+encodeURIComponent(name));return r.ok?await r.json():null}catch(e){return null}}
function normalise(c,confidence){const text=(c.card_faces||[c]).map(f=>f.oracle_text||'').filter(Boolean).join('\n—\n');return{name:c.name,type_line:c.type_line,image:c.image_uris?.normal||c.card_faces?.[0]?.image_uris?.normal||'',oracle:text,confidence:Number(confidence)||null,keywords:detect(text)}}
function detect(text){const low=text.toLowerCase();return Object.entries(definitions).filter(([k])=>low.includes(k)).map(([k,v])=>[title(k),v])}
function title(s){return s.charAt(0).toUpperCase()+s.slice(1)}
$('#demoBtn').onclick=()=>{currentCard=DEMO;fillConfirm(DEMO);show('confirm')};
function fillConfirm(c){$('#matchedImage').src=c.image;$('#matchedName').textContent=c.name;$('#matchedType').textContent=c.type_line;$('#confidence').textContent=c.confidence?`${Math.round(c.confidence)}% identification confidence`:'Collection sample'}
$('#yesBtn').onclick=()=>{render(currentCard);save(currentCard);show('result')};
function curatorNote(c){const n=c.name.toLowerCase(),t=c.type_line.toLowerCase(),o=c.oracle.toLowerCase();if(n==='lightning greaves')return'A widely used protection piece that lets an important creature act at once.';if(n==='sol ring')return'One of the most influential mana artifacts ever printed.';if(n==='the one ring')return'A powerful source of cards whose cost becomes increasingly dangerous.';if(n==='birds of paradise')return'A foundational mana creature that has appeared in decks for decades.';if(o.includes('draw')&&o.includes('lose'))return'A source of additional cards that asks its controller to manage a growing cost.';if(t.includes('creature'))return'A creature whose place in the collection is defined by how it shapes combat and the board.';if(t.includes('instant'))return'A reactive spell designed to change the game at precisely the right moment.';if(t.includes('artifact'))return'An enduring tool whose influence continues while it remains on the battlefield.';return'A distinctive game piece whose printed text rewards careful timing and context.'}
function render(c){$('#resultImage').src=c.image;$('#resultName').textContent=c.name;$('#resultType').textContent=c.type_line;$('#collectionNote').textContent=curatorNote(c);$('#objectNumber').textContent=objectNo(c.name);const low=c.oracle.toLowerCase(),type=c.type_line.toLowerCase();const what=plainSummary(c);const timing=type.includes('instant')||low.includes('flash')?'Keep it available until its effect matters. Waiting preserves your options and gives opponents less information.':type.includes('sorcery')?'Cast it during your own main phase, when the board and available targets make its effect worthwhile.':type.includes('creature')?(low.includes('haste')?'Play it when immediate pressure or an immediate tap ability matters.':'Play it during a main phase to develop your board. It normally cannot attack until your next turn.'):'Most permanents are best introduced during your main phase, when you can afford them without surrendering an urgent response.';const use=low.includes('equip')?'Introduce a creature first, then attach this when you can also afford the equip cost. Move it when another creature becomes the more valuable carrier.':low.includes('destroy')||low.includes('exile target')?'Preserve it for a threat that truly matters rather than using it on the first legal target.':'Decide which role the card performs: developing the board, protecting a permanent, answering a threat or helping finish the game.';const watch=low.includes('shroud')?'Shroud also prevents your own targeted spells and abilities. Complete any other targeting before granting it.':low.includes('target')?'A target must remain legal when the spell or ability resolves. If every target becomes illegal, the effect does nothing.':'Consider the removal, blockers and responses an opponent may still possess before committing it.';$('#explanation').innerHTML=section('I','What it does',`<p>${esc(what)}</p><p class="quiet">Printed text: ${esc(c.oracle)}</p>`)+section('II','Glossary',c.keywords.length?c.keywords.map(([k,v])=>`<div class="glossary-entry"><b>${esc(k)}</b><p>${esc(v)}</p></div>`).join(''):'<p>This card contains no major keyword that requires translation.</p>')+section('III','When to play it',`<p>${esc(timing)}</p>`)+section('IV','Why experienced players use it',`<p>${esc(use)}</p>`)+section('V','Watch for',`<p>${esc(watch)}</p>`)}
function plainSummary(c){const type=c.type_line.toLowerCase(),o=c.oracle.toLowerCase();if(o.includes('haste')&&o.includes('shroud'))return`${c.name} protects a creature and allows it to act immediately.`;if(type.includes('instant'))return`${c.name} is a reactive spell intended to alter a key moment before it resolves.`;if(type.includes('sorcery'))return`${c.name} produces a one-time effect during its controller’s main phase.`;if(type.includes('creature'))return`${c.name} adds a creature to the battlefield, where its abilities influence combat or the wider board.`;if(type.includes('artifact'))return`${c.name} is a permanent tool whose effect remains available while it stays on the battlefield.`;return`${c.name} changes the game according to its printed rules text while it is in the relevant zone.`}
function section(n,h,b){return`<section class="note-section"><div class="index">${n}</div><div><h3>${h}</h3>${b}</div></section>`}
function objectNo(name){let x=0;for(const c of name)x=(x*31+c.charCodeAt(0))%999;return String(x||1).padStart(3,'0')}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function save(c){let list=JSON.parse(localStorage.getItem('spellcheck-field-notes')||'[]').filter(x=>x.name!==c.name);list.unshift({name:c.name,type:c.type_line,image:c.image,note:curatorNote(c)});localStorage.setItem('spellcheck-field-notes',JSON.stringify(list.slice(0,12)))}
$('#archiveBtn').onclick=()=>{const list=JSON.parse(localStorage.getItem('spellcheck-field-notes')||'[]');$('#archiveList').innerHTML=list.length?list.map(c=>`<button class="archive-item" data-name="${esc(c.name)}"><img src="${esc(c.image)}" alt=""><div><b>${esc(c.name)}</b><span>${esc(c.note)}</span></div></button>`).join(''):'<p class="empty-archive">No cards have been studied yet.</p>';$('#archiveDialog').showModal()};
$('#closeArchive').onclick=()=>$('#archiveDialog').close();
$('#archiveList').onclick=async e=>{const b=e.target.closest('[data-name]');if(!b)return;$('#archiveDialog').close();const found=await lookup(b.dataset.name);if(found){currentCard=normalise(found);render(currentCard);show('result')}};
$('#shareBtn').onclick=async()=>{try{await navigator.share({title:`${currentCard.name} — SpellCheck`,text:`Collection notes for ${currentCard.name}.`,url:location.href})}catch(e){toast('Sharing cancelled')}};
